*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 10:55:34 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:43525 (port auto-assigned) fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55ff968b5140
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8548)
spawned uWSGI worker 1 (pid: 8549, cores: 1)
spawned uWSGI http 1 (pid: 8550)
SIGINT/SIGTERM received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 8550)
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:02:25 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:37359 (port auto-assigned) fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55bdbe52d140
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9430)
spawned uWSGI worker 1 (pid: 9431, cores: 1)
spawned uWSGI http 1 (pid: 9432)
SIGINT/SIGTERM received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 9432)
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:10:49 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55eb8e95b050
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10457)
spawned uWSGI worker 1 (pid: 10458, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 10458|app: -1|req: -1/1] 192.168.1.113 () {44 vars in 821 bytes} [Fri Mar  4 11:10:51 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10458|app: -1|req: -1/2] 192.168.1.113 () {44 vars in 821 bytes} [Fri Mar  4 11:10:54 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:12:02 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55e0ed2f3050
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10617)
spawned uWSGI worker 1 (pid: 10618, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 10618|app: -1|req: -1/1] 192.168.1.113 () {44 vars in 821 bytes} [Fri Mar  4 11:12:09 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10618|app: -1|req: -1/2] 192.168.1.113 () {44 vars in 821 bytes} [Fri Mar  4 11:12:16 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10618|app: -1|req: -1/3] 192.168.1.111 () {44 vars in 703 bytes} [Fri Mar  4 11:13:34 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10618|app: -1|req: -1/4] 192.168.1.113 () {44 vars in 821 bytes} [Fri Mar  4 11:14:55 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10618|app: -1|req: -1/5] 192.168.1.111 () {40 vars in 668 bytes} [Fri Mar  4 11:15:01 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10618|app: -1|req: -1/6] 192.168.1.111 () {40 vars in 668 bytes} [Fri Mar  4 11:17:47 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10618|app: -1|req: -1/7] 192.168.1.111 () {40 vars in 668 bytes} [Fri Mar  4 11:17:47 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10618|app: -1|req: -1/8] 192.168.1.111 () {40 vars in 668 bytes} [Fri Mar  4 11:17:48 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10618|app: -1|req: -1/9] 192.168.1.111 () {40 vars in 668 bytes} [Fri Mar  4 11:17:48 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10618|app: -1|req: -1/10] 192.168.1.111 () {40 vars in 668 bytes} [Fri Mar  4 11:17:48 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10618|app: -1|req: -1/11] 192.168.1.111 () {38 vars in 647 bytes} [Fri Mar  4 11:18:05 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGTERM received...killing workers...
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:19:24 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x55bea40a5010
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 11651)
spawned uWSGI worker 1 (pid: 11652, cores: 2)
worker 1 buried after 1 seconds
goodbye to uWSGI.
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:24:46 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x55fb5d521010
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12335)
spawned uWSGI worker 1 (pid: 12336, cores: 2)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/zun/Python/day06/sanae_note/sanae_note
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:25:30 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x55ebee39a620
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12335)
spawned uWSGI worker 1 (pid: 12556, cores: 2)
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:26:52 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x55c6246b8d60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2916)
spawned uWSGI worker 1 (pid: 2917, cores: 2)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:32:48 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x561fccbf9d60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4587)
spawned uWSGI worker 1 (pid: 4588, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 4588|app: -1|req: -1/1] 192.168.1.113 () {44 vars in 811 bytes} [Fri Mar  4 11:32:50 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 4588|app: -1|req: -1/2] 192.168.1.113 () {42 vars in 790 bytes} [Fri Mar  4 11:32:54 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
SIGINT/SIGTERM received...killing workers...
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:36:05 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x55ea25b91d60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
worker 1 buried after 1 seconds
goodbye to uWSGI.
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4967)
spawned uWSGI worker 1 (pid: 4968, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 4968|app: -1|req: -1/1] 192.168.1.111 () {40 vars in 668 bytes} [Fri Mar  4 11:37:02 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 4968|app: -1|req: -1/2] 192.168.1.111 () {38 vars in 647 bytes} [Fri Mar  4 11:37:17 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 4968|app: -1|req: -1/3] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:37:29 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 4968|app: -1|req: -1/4] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:37:30 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 4968|app: -1|req: -1/5] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:37:30 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 4968|app: -1|req: -1/6] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:37:30 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 4968|app: -1|req: -1/7] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:37:30 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 4968|app: -1|req: -1/8] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:37:30 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 4968|app: -1|req: -1/9] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:37:31 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 4968|app: -1|req: -1/10] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:37:31 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 4968|app: -1|req: -1/11] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:37:33 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 4968|app: -1|req: -1/12] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:37:35 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 4968|app: -1|req: -1/13] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:37:56 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGTERM received...killing workers...
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:39:00 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8001).
bind(): Address already in use [core/socket.c line 769]
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:39:40 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x5573b9bf9d60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5546)
spawned uWSGI worker 1 (pid: 5547, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 5547|app: -1|req: -1/1] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:39:45 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5547|app: -1|req: -1/2] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:39:47 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 5547|app: -1|req: -1/3] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:39:47 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5547|app: -1|req: -1/4] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:39:48 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 5547|app: -1|req: -1/5] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:39:48 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5547|app: -1|req: -1/6] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:39:48 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 5547|app: -1|req: -1/7] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:39:48 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5547|app: -1|req: -1/8] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:39:48 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 5547|app: -1|req: -1/9] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:39:48 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5547|app: -1|req: -1/10] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:39:49 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 5547|app: -1|req: -1/11] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:39:50 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 5547|app: -1|req: -1/12] 192.168.1.111 () {40 vars in 678 bytes} [Fri Mar  4 11:40:25 2022] GET /index => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:43:35 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x55dda412cd60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5997)
spawned uWSGI worker 1 (pid: 5998, cores: 2)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 5998)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/zun/Python/day06/sanae_note/sanae_note
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (127.0.0.1:8001)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:43:48 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8001 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x556c14f1f5d0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5997)
spawned uWSGI worker 1 (pid: 6030, cores: 2)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 11:45:15 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x55d7c8fadd60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6264)
spawned uWSGI worker 1 (pid: 6265, cores: 2)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 15:15:01 2022] ***
compiled with version: 9.3.0 on 02 March 2022 13:46:37
os: Linux-5.13.0-1014-azure #16~20.04.1-Ubuntu SMP Wed Feb 16 20:56:59 UTC 2022
nodename: azure
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/zun/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/zun/sanae_note
your processes number limit is 3606
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x563df75313b0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x563df75313b0 pid: 1864 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1864)
spawned uWSGI worker 1 (pid: 1866, cores: 1)
Not Found: /
[pid: 1866|app: 0|req: 1/1] 103.142.140.81 () {42 vars in 855 bytes} [Fri Mar  4 15:15:08 2022] GET / => generated 2833 bytes in 48 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 1866|app: 0|req: 2/2] 103.142.140.81 () {42 vars in 884 bytes} [Fri Mar  4 15:15:16 2022] GET /index => generated 233 bytes in 10 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1866|app: 0|req: 3/3] 103.142.140.81 () {44 vars in 932 bytes} [Fri Mar  4 15:15:18 2022] GET /user/reg => generated 506 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
Forbidden (CSRF token missing or incorrect.): /user/reg
[pid: 1866|app: 0|req: 4/4] 103.142.140.81 () {52 vars in 1116 bytes} [Fri Mar  4 15:15:25 2022] POST /user/reg => generated 2514 bytes in 3 msecs (HTTP/1.1 403) 5 headers in 159 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 15:16:26 2022] ***
compiled with version: 9.3.0 on 02 March 2022 13:46:37
os: Linux-5.13.0-1014-azure #16~20.04.1-Ubuntu SMP Wed Feb 16 20:56:59 UTC 2022
nodename: azure
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/zun/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/zun/sanae_note
your processes number limit is 3606
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55d19aa453b0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55d19aa453b0 pid: 1899 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1899)
spawned uWSGI worker 1 (pid: 1901, cores: 1)
Not Found: /
[pid: 1901|app: 0|req: 1/1] 103.142.140.81 () {42 vars in 874 bytes} [Fri Mar  4 15:16:33 2022] GET / => generated 2833 bytes in 46 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 1901|app: 0|req: 2/2] 103.142.140.81 () {42 vars in 884 bytes} [Fri Mar  4 15:16:37 2022] GET /index => generated 233 bytes in 7 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1901|app: 0|req: 3/3] 103.142.140.81 () {44 vars in 932 bytes} [Fri Mar  4 15:16:39 2022] GET /user/reg => generated 506 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
[pid: 1901|app: 0|req: 4/4] 103.142.140.81 () {52 vars in 1116 bytes} [Fri Mar  4 15:16:47 2022] POST /user/reg => generated 0 bytes in 39 msecs (HTTP/1.1 302) 8 headers in 344 bytes (1 switches on core 0)
[pid: 1901|app: 0|req: 5/5] 103.142.140.81 () {46 vars in 1004 bytes} [Fri Mar  4 15:16:47 2022] GET /index => generated 258 bytes in 6 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1901|app: 0|req: 6/6] 103.142.140.81 () {44 vars in 988 bytes} [Fri Mar  4 15:16:49 2022] GET /note/list_note => generated 617 bytes in 7 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1901|app: 0|req: 7/7] 103.142.140.81 () {44 vars in 985 bytes} [Fri Mar  4 15:16:51 2022] GET /note/add => generated 398 bytes in 4 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1901|app: 0|req: 8/8] 103.142.140.81 () {52 vars in 1162 bytes} [Fri Mar  4 15:17:12 2022] POST /note/add => generated 0 bytes in 18 msecs (HTTP/1.1 302) 7 headers in 208 bytes (1 switches on core 0)
[pid: 1901|app: 0|req: 9/9] 103.142.140.81 () {46 vars in 1022 bytes} [Fri Mar  4 15:17:12 2022] GET /note/list_note => generated 1059 bytes in 36 msecs (HTTP/1.1 200) 6 headers in 181 bytes (1 switches on core 0)
Internal Server Error: /note/page_note/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'sanae_note.my_cache_table' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zun/sanae_note/./note/views.py", line 16, in wrap
    return fn(request,*args,**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 122, in _wrapped_view
    result = middleware.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/cache.py", line 145, in process_request
    cache_key = get_cache_key(request, self.key_prefix, 'GET', cache=self.cache)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/cache.py", line 362, in get_cache_key
    headerlist = cache.get(cache_key)
  File "/usr/local/lib/python3.8/dist-packages/django/core/cache/backends/db.py", line 51, in get
    return self.get_many([key], version).get(key, default)
  File "/usr/local/lib/python3.8/dist-packages/django/core/cache/backends/db.py", line 68, in get_many
    cursor.execute(
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'sanae_note.my_cache_table' doesn't exist")
[pid: 1901|app: 0|req: 10/10] 103.142.140.81 () {44 vars in 1001 bytes} [Fri Mar  4 15:17:14 2022] GET /note/page_note/1 => generated 186988 bytes in 63 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
Internal Server Error: /note/page_note/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'sanae_note.my_cache_table' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zun/sanae_note/./note/views.py", line 16, in wrap
    return fn(request,*args,**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 122, in _wrapped_view
    result = middleware.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/cache.py", line 145, in process_request
    cache_key = get_cache_key(request, self.key_prefix, 'GET', cache=self.cache)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/cache.py", line 362, in get_cache_key
    headerlist = cache.get(cache_key)
  File "/usr/local/lib/python3.8/dist-packages/django/core/cache/backends/db.py", line 51, in get
    return self.get_many([key], version).get(key, default)
  File "/usr/local/lib/python3.8/dist-packages/django/core/cache/backends/db.py", line 68, in get_many
    cursor.execute(
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'sanae_note.my_cache_table' doesn't exist")
[pid: 1901|app: 0|req: 11/11] 103.142.140.81 () {44 vars in 1001 bytes} [Fri Mar  4 15:17:28 2022] GET /note/page_note/1 => generated 186988 bytes in 54 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
[pid: 1901|app: 0|req: 12/12] 103.142.140.81 () {44 vars in 979 bytes} [Fri Mar  4 15:17:54 2022] GET /index => generated 258 bytes in 5 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
Not Found: /
[pid: 1901|app: 0|req: 13/13] 103.142.140.81 () {42 vars in 918 bytes} [Fri Mar  4 15:18:01 2022] GET / => generated 2833 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 1901|app: 0|req: 14/14] 103.142.140.81 () {42 vars in 946 bytes} [Fri Mar  4 15:18:09 2022] GET /note/list_note => generated 1059 bytes in 7 msecs (HTTP/1.1 200) 6 headers in 181 bytes (1 switches on core 0)
Not Found: /
[pid: 1901|app: 0|req: 15/15] 103.142.140.81 () {42 vars in 918 bytes} [Fri Mar  4 15:18:16 2022] GET / => generated 2833 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 1901|app: 0|req: 16/16] 103.142.140.81 () {42 vars in 934 bytes} [Fri Mar  4 15:18:22 2022] GET /user/reg => generated 506 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
Not Found: /
[pid: 1901|app: 0|req: 17/17] 103.142.140.81 () {42 vars in 918 bytes} [Fri Mar  4 15:18:25 2022] GET / => generated 2833 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 1901|app: 0|req: 18/18] 103.142.140.81 () {42 vars in 940 bytes} [Fri Mar  4 15:18:38 2022] GET /test_upload => generated 366 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
[pid: 1901|app: 0|req: 19/19] 103.142.140.81 () {52 vars in 1247 bytes} [Fri Mar  4 15:19:24 2022] POST /test_upload => generated 33 bytes in 15 msecs (HTTP/1.1 200) 5 headers in 165 bytes (6 switches on core 0)
[pid: 1901|app: 0|req: 20/20] 103.142.140.81 () {42 vars in 940 bytes} [Fri Mar  4 15:19:26 2022] GET /test_upload => generated 366 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 1901|app: 0|req: 21/21] 218.85.118.194 () {40 vars in 718 bytes} [Fri Mar  4 15:32:16 2022] GET /favicon.ico => generated 2884 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 15:48:34 2022] ***
compiled with version: 9.3.0 on 02 March 2022 13:46:37
os: Linux-5.13.0-1014-azure #16~20.04.1-Ubuntu SMP Wed Feb 16 20:56:59 UTC 2022
nodename: azure
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/zun/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/zun/sanae_note
your processes number limit is 3606
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5651940683b0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5651940683b0 pid: 2335 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2335)
spawned uWSGI worker 1 (pid: 2337, cores: 1)
Not Found: /
[pid: 2337|app: 0|req: 1/1] 103.142.140.81 () {42 vars in 899 bytes} [Fri Mar  4 15:48:44 2022] GET / => generated 2833 bytes in 45 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 2/2] 103.142.140.81 () {44 vars in 952 bytes} [Fri Mar  4 15:48:52 2022] GET /index => generated 233 bytes in 15 msecs (HTTP/1.1 200) 7 headers in 279 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 3/3] 103.142.140.81 () {42 vars in 884 bytes} [Fri Mar  4 15:48:52 2022] GET /index => generated 233 bytes in 2 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 4/4] 103.142.140.81 () {44 vars in 932 bytes} [Fri Mar  4 15:48:54 2022] GET /user/reg => generated 506 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 5/5] 103.142.140.81 () {44 vars in 936 bytes} [Fri Mar  4 15:48:56 2022] GET /user/login => generated 509 bytes in 2 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 6/6] 103.142.140.81 () {52 vars in 1122 bytes} [Fri Mar  4 15:49:07 2022] POST /user/login => generated 0 bytes in 20 msecs (HTTP/1.1 302) 10 headers in 520 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 7/7] 103.142.140.81 () {46 vars in 1030 bytes} [Fri Mar  4 15:49:07 2022] GET /index => generated 258 bytes in 5 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 8/8] 103.142.140.81 () {44 vars in 1012 bytes} [Fri Mar  4 15:49:08 2022] GET /note/list_note => generated 1931 bytes in 25 msecs (HTTP/1.1 200) 6 headers in 181 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 9/9] 103.142.140.81 () {44 vars in 1025 bytes} [Fri Mar  4 15:49:10 2022] GET /note/page_note/1 => generated 325 bytes in 56 msecs (HTTP/1.1 200) 8 headers in 248 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 10/10] 103.142.140.81 () {44 vars in 1025 bytes} [Fri Mar  4 15:49:12 2022] GET /note/page_note/3 => generated 324 bytes in 67 msecs (HTTP/1.1 200) 8 headers in 248 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 11/11] 103.142.140.81 () {44 vars in 1025 bytes} [Fri Mar  4 15:49:15 2022] GET /note/page_note/5 => generated 312 bytes in 54 msecs (HTTP/1.1 200) 8 headers in 248 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 12/12] 103.142.140.81 () {44 vars in 1009 bytes} [Fri Mar  4 15:49:17 2022] GET /note/add => generated 398 bytes in 9 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 13/13] 103.142.140.81 () {44 vars in 1003 bytes} [Fri Mar  4 15:49:19 2022] GET /index => generated 258 bytes in 5 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 14/14] 103.142.140.81 () {44 vars in 1006 bytes} [Fri Mar  4 15:49:21 2022] GET /user/logout => generated 0 bytes in 18 msecs (HTTP/1.1 302) 10 headers in 507 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 15/15] 103.142.140.81 () {44 vars in 970 bytes} [Fri Mar  4 15:49:22 2022] GET /index => generated 233 bytes in 5 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 16/16] 103.142.140.81 () {44 vars in 980 bytes} [Fri Mar  4 15:49:23 2022] GET /user/login => generated 509 bytes in 5 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 17/17] 103.142.140.81 () {42 vars in 928 bytes} [Fri Mar  4 15:49:38 2022] GET /media => generated 0 bytes in 0 msecs (HTTP/1.1 301) 5 headers in 175 bytes (1 switches on core 0)
Not Found: /media/
[pid: 2337|app: 0|req: 18/18] 103.142.140.81 () {42 vars in 930 bytes} [Fri Mar  4 15:49:38 2022] GET /media/ => generated 3025 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /media/picture
[pid: 2337|app: 0|req: 19/19] 103.142.140.81 () {42 vars in 944 bytes} [Fri Mar  4 15:50:13 2022] GET /media/picture => generated 3046 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 20/20] 103.142.140.81 () {42 vars in 976 bytes} [Fri Mar  4 15:50:21 2022] GET /media/picture/89396932_p0.jpg => generated 212899 bytes in 6 msecs via sendfile() (HTTP/1.1 200) 7 headers in 258 bytes (0 switches on core 0)
[pid: 2337|app: 0|req: 21/21] 103.142.140.81 () {42 vars in 976 bytes} [Fri Mar  4 15:50:32 2022] GET /media/picture/91104232_p0.jpg => generated 2627926 bytes in 9 msecs via sendfile() (HTTP/1.1 200) 7 headers in 259 bytes (0 switches on core 0)
[pid: 2337|app: 0|req: 22/22] 103.142.140.81 () {42 vars in 976 bytes} [Fri Mar  4 15:50:46 2022] GET /media/picture/92677374_p0.jpg => generated 533312 bytes in 3 msecs via sendfile() (HTTP/1.1 200) 7 headers in 258 bytes (0 switches on core 0)
Not Found: /media/picture
[pid: 2337|app: 0|req: 23/23] 103.142.140.81 () {42 vars in 944 bytes} [Fri Mar  4 15:51:50 2022] GET /media/picture => generated 3046 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /
[pid: 2337|app: 0|req: 24/24] 103.142.140.81 () {42 vars in 918 bytes} [Fri Mar  4 15:53:54 2022] GET / => generated 2833 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 25/25] 103.142.140.81 () {42 vars in 938 bytes} [Fri Mar  4 15:54:08 2022] GET /page_test/ => generated 877 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 26/26] 103.142.140.81 () {44 vars in 996 bytes} [Fri Mar  4 15:54:10 2022] GET /page_test?page=2 => generated 0 bytes in 0 msecs (HTTP/1.1 301) 5 headers in 186 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 27/27] 103.142.140.81 () {44 vars in 998 bytes} [Fri Mar  4 15:54:10 2022] GET /page_test/?page=2 => generated 907 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 28/28] 103.142.140.81 () {44 vars in 1003 bytes} [Fri Mar  4 15:54:11 2022] GET /page_test?page=3 => generated 0 bytes in 0 msecs (HTTP/1.1 301) 5 headers in 186 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 29/29] 103.142.140.81 () {44 vars in 1005 bytes} [Fri Mar  4 15:54:11 2022] GET /page_test/?page=3 => generated 911 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 30/30] 103.142.140.81 () {44 vars in 1003 bytes} [Fri Mar  4 15:54:12 2022] GET /page_test?page=4 => generated 0 bytes in 0 msecs (HTTP/1.1 301) 5 headers in 186 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 31/31] 103.142.140.81 () {44 vars in 1005 bytes} [Fri Mar  4 15:54:12 2022] GET /page_test/?page=4 => generated 876 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 32/32] 103.142.140.81 () {44 vars in 1005 bytes} [Fri Mar  4 15:54:13 2022] GET /page_test/?page=3 => generated 911 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 33/33] 103.142.140.81 () {44 vars in 1005 bytes} [Fri Mar  4 15:54:14 2022] GET /page_test/?page=2 => generated 907 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 34/34] 103.142.140.81 () {44 vars in 1003 bytes} [Fri Mar  4 15:54:15 2022] GET /page_test?page=1 => generated 0 bytes in 0 msecs (HTTP/1.1 301) 5 headers in 186 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 35/35] 103.142.140.81 () {44 vars in 1005 bytes} [Fri Mar  4 15:54:15 2022] GET /page_test/?page=1 => generated 877 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 36/36] 103.142.140.81 () {44 vars in 1005 bytes} [Fri Mar  4 15:54:18 2022] GET /page_test/?page=2 => generated 907 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 37/37] 103.142.140.81 () {44 vars in 1005 bytes} [Fri Mar  4 15:54:19 2022] GET /page_test/?page=3 => generated 911 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 38/38] 103.142.140.81 () {44 vars in 1005 bytes} [Fri Mar  4 15:54:20 2022] GET /page_test/?page=2 => generated 907 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 39/39] 103.142.140.81 () {44 vars in 1005 bytes} [Fri Mar  4 15:54:21 2022] GET /page_test/?page=1 => generated 877 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
Not Found: /
[pid: 2337|app: 0|req: 40/40] 103.142.140.81 () {42 vars in 918 bytes} [Fri Mar  4 15:54:26 2022] GET / => generated 2833 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 41/41] 103.142.140.81 () {42 vars in 936 bytes} [Fri Mar  4 15:54:35 2022] GET /test_mail => generated 317 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 166 bytes (1 switches on core 0)
Not Found: /
[pid: 2337|app: 0|req: 42/42] 103.142.140.81 () {44 vars in 949 bytes} [Fri Mar  4 15:56:46 2022] GET / => generated 2833 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 43/43] 103.142.140.81 () {42 vars in 911 bytes} [Fri Mar  4 16:06:29 2022] GET /admin/ => generated 0 bytes in 18 msecs (HTTP/1.1 302) 9 headers in 331 bytes (1 switches on core 0)
[pid: 2337|app: 0|req: 44/44] 103.142.140.81 () {42 vars in 948 bytes} [Fri Mar  4 16:06:29 2022] GET /admin/login/?next=/admin/ => generated 2216 bytes in 25 msecs (HTTP/1.1 200) 9 headers in 461 bytes (1 switches on core 0)
Not Found: /
[pid: 2337|app: 0|req: 45/45] 103.142.140.81 () {42 vars in 918 bytes} [Fri Mar  4 16:07:08 2022] GET / => generated 2833 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /
[pid: 2337|app: 0|req: 46/46] 64.62.197.152 () {28 vars in 287 bytes} [Fri Mar  4 16:09:25 2022] GET / => generated 2833 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /.env
[pid: 2337|app: 0|req: 47/47] 185.254.196.223 () {36 vars in 505 bytes} [Fri Mar  4 16:10:21 2022] GET /.env => generated 2863 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /
[pid: 2337|app: 0|req: 48/48] 185.254.196.223 () {40 vars in 612 bytes} [Fri Mar  4 16:10:22 2022] POST / => generated 2834 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /
[pid: 2337|app: 0|req: 49/49] 45.146.165.37 () {36 vars in 529 bytes} [Fri Mar  4 16:16:37 2022] GET / => generated 2836 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /
[pid: 2337|app: 0|req: 50/50] 2.56.59.20 () {28 vars in 287 bytes} [Fri Mar  4 16:21:21 2022] GET / => generated 2836 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /HNAP1/
[pid: 2337|app: 0|req: 51/51] 2.56.59.20 () {40 vars in 647 bytes} [Fri Mar  4 16:21:22 2022] POST /HNAP1/ => generated 2873 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /api/v1/ui_theme
[pid: 2337|app: 0|req: 52/52] 161.189.134.11 () {42 vars in 730 bytes} [Fri Mar  4 16:49:16 2022] GET /api/v1/ui_theme => generated 2899 bytes in 4 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
